name: shoppe
description: "An ecommerce flutter app with python backend."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.2.0
  provider: ^6.1.5
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  dots_indicator: ^4.0.1
  flutter_svg: ^2.2.0
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^5.2.1
  pin_code_fields: ^8.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/shoppe_logo.png"
  min_sdk_android: 16 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
